[package]
name = "catscii"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
